### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by exitfiat** [ezzcodeezzlife/dalle2-in-python#18]
i run a little bot with your plugin and sometimes the picture generation fails and i get this error:

2022-08-23 09:34:15,255 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/satdress/.local/lib/python3.9/site-packages/telegram/ext/_application.py", line 983, in process_update
    await coroutine
  File "/home/satdress/.local/lib/python3.9/site-packages/telegram/ext/_handler.py", line 137, in handle_update
    return await self.callback(update, context)
  File "/home/satdress/dalle2telegrambot/main.py", line 62, in paid
    file_paths = dalle.generate_and_download(user_state[update.effective_chat.id][0])
  File "/home/satdress/.local/lib/python3.9/site-packages/dalle2/dalle2.py", line 31, in generate_and_download
    generations = self.generate(prompt)
  File "/home/satdress/.local/lib/python3.9/site-packages/dalle2/dalle2.py", line 28, in generate
    return self.get_task_response(body)
  File "/home/satdress/.local/lib/python3.9/site-packages/dalle2/dalle2.py", line 77, in get_task_response
    data = response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Is this related to the dalle2 module not returning something or am i understanding this completely wrong?

**Comment by ezzcodeezzlife** [comment]
would need more info about the project, but this probably isn't an issue from dalle2-in-python.

**Comment by exitfiat** [comment]
The project is [https://github.com/exitfiat/dalle2telegrambot](here) 
I think its a problem of the dalle plugin as it works since i put the generate command in try exception, or its a problem of the api itself. The error happens around 5% of all requests.

**Comment by ezzcodeezzlife** [comment]
will have another look at it 🔥
